version: "3.8"
services:
    app:
        build:
          context: .
          dockerfile: conf/Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
          - ./:/var/www
        networks:
            - laravel
        environment:
            - DB_HOST=mysql_laravel
            - REDIS_HOST=redis
    nginx_laravel:
        image: nginx:latest
        container_name: nginx_laravel
        restart: always
        volumes:
            - .:/var/www/
            - ./conf/conf.d/:/etc/nginx/conf.d/
        ports:
            - 8000:80
        networks:
            - laravel
    mysql_laravel:
        platform: linux/x86_64
        image: mysql
        tty: true
        container_name: mysql_laravel
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        volumes:
            - db:/var/lib/mysql
        networks:
            - laravel
    redis:
        image: redis
        container_name: cache
        restart: always
        ports:
            - 6379:6379
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
volumes:
    db:
